### PR TITLE
NONAME-154 fix error with deleted newline and add trimming

### PR DESCRIPTION
**Pull request by K4RP4T**

### CODE REVIEW

**Comment by sjerzykiewicz** [comment]
what do you think about removing extra newlines (like when there are more than two in a row) to keep questions and answers from having too much blank space?
image

**Comment by yanvoi** [comment]
> what do you think about removing extra newlines (like when there are more than two in a row) to keep questions and answers from having too much blank space? image

what if someone wishes to have more blank space though? I think we should manipulate user's input as little as possible.

**Comment by sjerzykiewicz** [comment]
> > > > what do you think about removing extra newlines (like when there are more than two in a row) to keep questions and answers from having too much blank space? image
> > > 
> > > 
> > > what if someone wishes to have more blank space though? I think we should manipulate user's input as little as possible.
> > 
> > 
> > We could maybe allow a maximum of 2 newlines in a row
> 
> imo we should just let everyone do as they please - it's not breaking anything is it?

Yeah, that's true. Should we add a character limit to each textbox? What would happen if survey_draft or answer exceeded the VARCHAR limit in PostgreSQL?

**Comment by yanvoi** [comment]
> Yeah, that's true. Should we add a character limit to each textbox? What would happen if survey_draft or answer exceeded the VARCHAR limit in PostgreSQL?

a character limit to a textbox wouldn't solve the problem as we keep whole survey structures in a single serialized entity.

"In addition, PostgreSQL provides the text type, which stores strings of any length." - currently the survey_structure field is of "character varying" type which does have some limit to how many characters it can store.

let's look into it an try mapping the survey_structure to the text type (if it's possible from the SQLModel level)

**Review by sjerzykiewicz — APPROVED** [review]

**Pull request merged**
